"""This package contains all the QT python classes that were autogenearted out of the .ui files by the PyQt5.uic.pyuic module.
It contains the following components:

    - About_ui.
    - cgdat_ui.
    - output_settings_ui.
    - progress_dialog_ui.
    - import_dialog_ui.

.. Note::
    Because these files were autogenerated no sphinx documentation is available for them. Go to the
    `pyqt documentation <http://pyqt.sourceforge.net/Docs/PyQt5/uic.html>`_ for more information.

"""

# Set all
__all__ = [
    "about_ui",
    "cgdat_ui",
    "output_settings_ui",
    "progress_dialog_ui",
    "import_dialog_ui",
]

# Import classes out of modules
from .about_ui import Ui_About
from .cgdat_ui import Ui_MainWindow
from .import_dialog_ui import Ui_ImportDialog
from .output_settings_ui import Ui_OutputSettings
from .progress_dialog_ui import Ui_ProgressDialog
from .splash_screen_ui import Ui_splash_screen
