# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ricks\OneDrive\Work\Wesley\qt\data_analyse.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(15, 15, 15, 0)
        self.gridLayout.setSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.control_group_box = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_group_box.sizePolicy().hasHeightForWidth())
        self.control_group_box.setSizePolicy(sizePolicy)
        self.control_group_box.setStyleSheet("QGroupBox{padding-top:15px; margin-top:-15px}")
        self.control_group_box.setTitle("")
        self.control_group_box.setObjectName("control_group_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.control_group_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.analyse_data_btn = QtWidgets.QPushButton(self.control_group_box)
        self.analyse_data_btn.setObjectName("analyse_data_btn")
        self.horizontalLayout.addWidget(self.analyse_data_btn)
        self.reset_conditions_grid_btn = QtWidgets.QPushButton(self.control_group_box)
        self.reset_conditions_grid_btn.setObjectName("reset_conditions_grid_btn")
        self.horizontalLayout.addWidget(self.reset_conditions_grid_btn)
        self.output_settings_btn = QtWidgets.QPushButton(self.control_group_box)
        self.output_settings_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../media/settings_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.output_settings_btn.setIcon(icon)
        self.output_settings_btn.setObjectName("output_settings_btn")
        self.horizontalLayout.addWidget(self.output_settings_btn)
        self.gridLayout.addWidget(self.control_group_box, 3, 0, 1, 1)
        self.settings_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.settings_group_box.setAutoFillBackground(False)
        self.settings_group_box.setObjectName("settings_group_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.settings_group_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.general_settings = QtWidgets.QGridLayout()
        self.general_settings.setObjectName("general_settings")
        self.input_file_path = QtWidgets.QLineEdit(self.settings_group_box)
        self.input_file_path.setEnabled(False)
        self.input_file_path.setText("")
        self.input_file_path.setReadOnly(True)
        self.input_file_path.setObjectName("input_file_path")
        self.general_settings.addWidget(self.input_file_path, 0, 2, 1, 1)
        self.time_range_te = QtWidgets.QLineEdit(self.settings_group_box)
        self.time_range_te.setEnabled(True)
        self.time_range_te.setText("")
        self.time_range_te.setReadOnly(True)
        self.time_range_te.setObjectName("time_range_te")
        self.general_settings.addWidget(self.time_range_te, 2, 2, 1, 1)
        self.time_range_lbl = QtWidgets.QLabel(self.settings_group_box)
        self.time_range_lbl.setObjectName("time_range_lbl")
        self.general_settings.addWidget(self.time_range_lbl, 2, 0, 1, 1)
        self.input_file_browser = QtWidgets.QToolButton(self.settings_group_box)
        self.input_file_browser.setObjectName("input_file_browser")
        self.general_settings.addWidget(self.input_file_browser, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.settings_group_box)
        self.label_2.setObjectName("label_2")
        self.general_settings.addWidget(self.label_2, 1, 0, 1, 1)
        self.output_file_path = QtWidgets.QLineEdit(self.settings_group_box)
        self.output_file_path.setEnabled(False)
        self.output_file_path.setText("")
        self.output_file_path.setReadOnly(True)
        self.output_file_path.setObjectName("output_file_path")
        self.general_settings.addWidget(self.output_file_path, 1, 2, 1, 1)
        self.output_file_browser = QtWidgets.QToolButton(self.settings_group_box)
        self.output_file_browser.setObjectName("output_file_browser")
        self.general_settings.addWidget(self.output_file_browser, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.settings_group_box)
        self.label.setObjectName("label")
        self.general_settings.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.general_settings, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.settings_group_box, 1, 0, 1, 1)
        self.conditions_group_box = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conditions_group_box.sizePolicy().hasHeightForWidth())
        self.conditions_group_box.setSizePolicy(sizePolicy)
        self.conditions_group_box.setStyleSheet("")
        self.conditions_group_box.setObjectName("conditions_group_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.conditions_group_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.conditions_group_box)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaContent = QtWidgets.QWidget()
        self.scrollAreaContent.setGeometry(QtCore.QRect(0, 0, 746, 302))
        self.scrollAreaContent.setObjectName("scrollAreaContent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaContent)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.conditions_grid = QtWidgets.QGridLayout()
        self.conditions_grid.setObjectName("conditions_grid")
        self.verticalLayout.addLayout(self.conditions_grid)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaContent)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.conditions_grid2 = QtWidgets.QGridLayout()
        self.conditions_grid2.setObjectName("conditions_grid2")
        self.verticalLayout_3.addLayout(self.conditions_grid2)
        self.gridLayout.addWidget(self.conditions_group_box, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../media/about_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.analyse_data_btn.setText(_translate("MainWindow", "Analyse Data"))
        self.reset_conditions_grid_btn.setText(_translate("MainWindow", "Reset Fields"))
        self.settings_group_box.setTitle(_translate("MainWindow", "Settings"))
        self.time_range_lbl.setText(_translate("MainWindow", "Time range"))
        self.input_file_browser.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "Ouput file"))
        self.output_file_browser.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Input file"))
        self.conditions_group_box.setTitle(_translate("MainWindow", "Conditions"))
        self.menuFile.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

